@startuml diagramaClases

interface Usuario{
  - number id
  - string nombres
  - string descripcion 
  - string correo
  - string contraseña
  - date fechaRegistro
  - date fechaNacimiento
  - boolean genero
}

enum Permisos{
  CREAR, 
  LEER, 
  ACTUALIZAR, 
  ELIMINAR
}

class Admin{
  - number id
  - string nombre
  - string contraseña
}
Admin "1" --> "*" Permisos: all
Admin "1" --> "*" Aprendiz

class Asesor implements Usuario{
  - boolean estado
  - string ocupacion
  - date[] disponible
}
Asesor "1" --o "*" Aprendiz
Asesor "1" --> "*" Compentencia 
Asesor "1" --> "2" Permisos : L, A

class Aprendiz implements Usuario{
  - boolean pago
}
Aprendiz "1" --> "1" Categoria  
Aprendiz "1" --o "1" Asesor
Aprendiz "1" --> "2" Permisos : L, A

class Categoria{
  - number id
  - string nombre
}
Categoria "1" --> "*" Compentencia

class Compentencia {
  - number id
  - string nombre
  - string descripcion
}
@enduml